version: '3.5'
services:
  postgreSQL:
    container_name: postgress-test
    image: "postgres:latest"
    env_file:
      - database.env
    volumes:
      - /database-data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

volumes:
  database-data:
    driver: local
